### ISSUE TITLE
feature request: prefix 和 postfix

### ISSUE THREAD

**Issue by tanloong** [LintaoAmons/easy-commands.nvim#1]
1. 执行之后得到的 output，有时需要用字符包裹起来，比如md里的3个反引号，LaTeX里的\begin{verbatim}和\end{verbatim}。能不能加一个自定义的prefix和postfix字符，让output=prefix+output+postfix？

2. 有时可能 output 的头部和尾部是唯一需要编辑的地方，有了 prefix 和 postfix 就节省了这一步。能不能加一个把光标移动到 output 末尾的选项？那样就可以继续写新的内容了。

**Comment by LintaoAmons** [comment]
加了朋友，具体配置可以参考
https://github.com/LintaoAmons/CoolStuffes/blob/1ff2c91c0c1468339979e9ac7af8b1e90500940e/lvim/.config/lvim/lua/lintao/plugins.lua#L7
