### ISSUE TITLE
feature request: 执行光标所在行

### ISSUE THREAD

**Issue by tanloong** [LintaoAmons/easy-commands.nvim#3]
能不能加一个执行光标所在行的功能？那样就不需要进入可视模式了。

判断当前是否处于visual模式，如果是，执行选中内容；否则执行当前行。

P.S.
```lua
local command = vim.fn.getline(".") -- 获取光标所在行的内容
```

**Comment by LintaoAmons** [comment]
RunCurrentLineAndOutput
RunCurrentLineAndOutputWithPrePostFix

加了这两个命令，你说的检测是不是处于 visual 模式我也想做，有空加上去
